// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sleep
{
    [SleepResourceType("sleep:index:Sleep")]
    public partial class Sleep : global::Pulumi.CustomResource
    {
        [Output("result")]
        public Output<string> Result { get; private set; } = null!;

        [Output("seconds")]
        public Output<int> Seconds { get; private set; } = null!;


        /// <summary>
        /// Create a Sleep resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Sleep(string name, SleepArgs args, CustomResourceOptions? options = null)
            : base("sleep:index:Sleep", name, args ?? new SleepArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Sleep(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sleep:index:Sleep", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Sleep resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Sleep Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Sleep(name, id, options);
        }
    }

    public sealed class SleepArgs : global::Pulumi.ResourceArgs
    {
        [Input("seconds", required: true)]
        public Input<int> Seconds { get; set; } = null!;

        public SleepArgs()
        {
        }
        public static new SleepArgs Empty => new SleepArgs();
    }
}
