# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .sleep import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "sleep",
  "mod": "index",
  "fqn": "pulumi_sleep",
  "classes": {
   "sleep:index:Sleep": "Sleep"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "sleep",
  "token": "pulumi:providers:sleep",
  "fqn": "pulumi_sleep",
  "class": "Provider"
 }
]
"""
)
